"""users table

Revision ID: 86e47163db68
Revises: 
Create Date: 2018-07-16 15:22:11.421546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e47163db68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('city', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'teams', ['city'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_column('teams', 'city')
    # ### end Alembic commands ###
