"""empty message

Revision ID: 30014d22b32e
Revises: 
Create Date: 2018-07-15 23:47:13.412852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30014d22b32e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
